/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import java.awt.Frame;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Vitor
 */
public class GUI_Principal extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Principal
     */
    public GUI_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Btn_start = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Geometria Computacional");

        jLabel1.setText("Escolha o Problema");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Area do Círculo", "Area do Polígono", "Convexidade do Poligono", "Distância entre 2 Pontos", "Distância entre Ponto e Reta", "Dobrar Polígono", "Intersecção de Segmento de Retas", "Ponto dentro do Polígono", "Ponto Próximo de um Segmento de Reta", "Predicado de Orientação 2D", "Circulo Mínimo", "Par Mais Próximo", "Problema da Mochila", "Troco Mínimo" }));

        Btn_start.setText("Iniciar");
        Btn_start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_startMouseClicked(evt);
            }
        });
        Btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_startActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_start)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(Btn_start)
                .addGap(46, 46, 46))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_startMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_Btn_startMouseClicked

    private void Btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_startActionPerformed
        // TODO add your handling code here:
        //Interface_Area_Circulo GUI_Circulo = new Interface_Area_Circulo();
        //GUI_Circulo.setVisible(true);
        int id = jComboBox1.getSelectedIndex();
        if (id >= 0) {
            switch (id) {
                case 0:
                    System.out.println("Area do Círculo!");
                    Interface_Area_Circulo GUI_Circulo = new Interface_Area_Circulo();
                    GUI_Circulo.setVisible(true);
                    break;
                case 1:
                    System.out.println("Area do Poligono");
                    Interface_Area_Poligono GUI_Pol = new Interface_Area_Poligono();
                    GUI_Pol.setVisible(true);
                    break;
                case 2:
                    System.out.println("Convexidade");
                    Interface_Convexidade_Poligono GUI_convex = new Interface_Convexidade_Poligono();
                    GUI_convex.setVisible(true);
                    break;
                case 3:
                    System.out.println("Distancia Entre Pontos");
                    Interface_Distancia_Pontos GUI_Pontos = new Interface_Distancia_Pontos();
                    GUI_Pontos.setVisible(true);
                    break;
                case 4:
                    System.out.println("Distancia entre Ponto e Reta");
                    Interface_Distancia_Ponto_Reta GUI_Pt_Reta = new Interface_Distancia_Ponto_Reta();
                    GUI_Pt_Reta.setVisible(true);
                    break;
                case 5:
                    System.out.println("Dobrar Poligono");
                    Interface_Dobrar_Poligono GUI_Dobra = new Interface_Dobrar_Poligono();
                    GUI_Dobra.setVisible(true);
                    break;
                case 6:
                    System.out.println("Intersecção de Segmento de Retas");
                    Interface_Interseccao_Seg_Reta GUI_Interseccao = new Interface_Interseccao_Seg_Reta();
                    GUI_Interseccao.setVisible(true);
                    break;
                case 7:
                    System.out.println("Ponto dentro do Poligono");
                    Interface_Ponto_In_Poligono GUI_Ponto_In_Pol = new Interface_Ponto_In_Poligono();
                    GUI_Ponto_In_Pol.setVisible(true);
                    break;
                case 8:
                    System.out.println("Ponto Próximo de um segmento de Reta");
                    Interface_Ponto_Prox_Seg_Reta GUI_Ponto_Prox_Seg_Reta = new Interface_Ponto_Prox_Seg_Reta();
                    GUI_Ponto_Prox_Seg_Reta.setVisible(true);
                    break;
                case 9:
                    System.out.println("Predicado 2D");
                    Interface_Predicado_2D GUI_2D = new Interface_Predicado_2D();
                    GUI_2D.setVisible(true);
                    break;
                case 10:
                    System.out.println("Circulo Minimo");
                    Interface_Circulo_Minimo GUI_Circulo_min = new Interface_Circulo_Minimo();
                    GUI_Circulo_min.setVisible(true);
                    break;
                case 11:
                    System.out.println("Par mais Próximo");
                    Interface_Par_Prox GUI_par_prox = new Interface_Par_Prox();
                    GUI_par_prox.setVisible(true);
                    break;
                case 12:
                    System.out.println("Problema da Mochila");
                    Interface_Mochila GUI_Mochila = new Interface_Mochila();
                    GUI_Mochila.setVisible(true);
                    break;
                case 13:
                    System.out.println("Troco Mínimo");
                    Interface_Troco_Minimo GUI_Troco = new Interface_Troco_Minimo();
                    GUI_Troco.setVisible(true);
                    break;
                /*case 14:
                    System.out.println("Voronoi");
                    Interface_Voronoi_2 GUI_Voronoi = new Interface_Voronoi_2();
                    break;*/
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Erro");
            throw new RuntimeException("Erro na escolha!");
        }
    }//GEN-LAST:event_Btn_startActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_start;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
