/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Modelo.Poligono;
import Modelo.Ponto;
import Problemas.Problemas_Classicos;
import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Vitor
 */
public class Interface_Convexidade_Poligono extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Convexidade_Poligono
     */
    public static ArrayList<Ponto> lista_Ponto;
    public static int state;
    private Problemas_Classicos classicos = new Problemas_Classicos();
    private boolean desenha = false;
    private boolean limpar = false;
    double mouseX, mouseY;

    public Interface_Convexidade_Poligono() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Verificação = new javax.swing.JButton();
        jPanel1 = jPanel1 = new javax.swing.JPanel() {
            @Override
            public void paintComponent(Graphics g) {
                g.clearRect(0, 0, this.getWidth(), this.getHeight());
                g.setColor(Color.RED);

                if (desenha) {

                    if (state == 0) {
                        g.fillOval((int) lista_Ponto.get(state).x -3, (int) lista_Ponto.get(state).y -3, 7, 7);
                        g.drawLine((int) lista_Ponto.get(state).x , (int) lista_Ponto.get(state).y, (int) mouseX,
                            (int) mouseY);
                    } else {
                        for (int i = 0; i < lista_Ponto.size() - 1; i++) {
                            g.fillOval((int) lista_Ponto.get(i).x -3, (int) lista_Ponto.get(i).y -3, 7, 7);
                            g.drawLine((int) (int) lista_Ponto.get(i).x, (int) lista_Ponto.get(i).y,
                                (int) lista_Ponto.get(i + 1).x, (int) lista_Ponto.get(i + 1).y);
                        }
                        g.fillOval((int) lista_Ponto.get(lista_Ponto.size() - 1).x -3,
                            (int) lista_Ponto.get(lista_Ponto.size() - 1).y -3, 7, 7);
                        g.drawLine((int) lista_Ponto.get(lista_Ponto.size() - 1).x,
                            (int) lista_Ponto.get(lista_Ponto.size() - 1).y, (int) lista_Ponto.get(0).x,
                            (int) lista_Ponto.get(0).y);

                    }

                }

            }
        };
        Btn_Limpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Geometria Computacional - Convexidade");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        btn_Verificação.setText("Iniciar Verificação");
        btn_Verificação.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_VerificaçãoMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );

        Btn_Limpar.setText("Apagar");
        Btn_Limpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_LimparMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 348, Short.MAX_VALUE)
                        .addComponent(Btn_Limpar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Verificação))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Verificação)
                    .addComponent(Btn_Limpar))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        state = 0;
        lista_Ponto = new ArrayList<>();
        mouseX = 0;
        mouseY = 0;
    }//GEN-LAST:event_formWindowActivated

    private void btn_VerificaçãoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_VerificaçãoMouseClicked
        // TODO add your handling code here:
        Poligono p = new Poligono();
        lista_Ponto.forEach((ponto) -> {
            p.insereVertice(ponto);
        });
        boolean resultado = classicos.PredicadoPoligonoConvexo(p);

        String texto;

        if (resultado) {
            texto = "Poligono Convexo";
        } else {
            texto = "Poligono Não Convexo";
        }

        JOptionPane.showMessageDialog(null, texto);
    }//GEN-LAST:event_btn_VerificaçãoMouseClicked

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:
        mouseX = evt.getX();
        mouseY = evt.getY();

        jPanel1.repaint();
    }//GEN-LAST:event_jPanel1MouseMoved

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        Ponto aux = new Ponto(evt.getX(), evt.getY());

        if (lista_Ponto.isEmpty()) {
            lista_Ponto.add(aux);
            desenha = true;
        } else {
            lista_Ponto.add(aux);
            state++;
        }

        if (state >= 2) {
            btn_Verificação.setEnabled(true);
        }

        jPanel1.repaint();
    }//GEN-LAST:event_jPanel1MousePressed

    private void Btn_LimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_LimparMouseClicked
        // TODO add your handling code here:
        desenha = false;
        btn_Verificação.setEnabled(false);
        state = 0;
        lista_Ponto.clear();
        jPanel1.repaint();
    }//GEN-LAST:event_Btn_LimparMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface_Convexidade_Poligono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface_Convexidade_Poligono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface_Convexidade_Poligono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface_Convexidade_Poligono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface_Convexidade_Poligono().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Limpar;
    private javax.swing.JButton btn_Verificação;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
