/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Modelo.Ponto;
import Problemas.ParMaisProximo;
import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;

/**
 * Divisão e Conquista
 *
 * @author Vitor
 */
public class Interface_Par_Prox extends javax.swing.JFrame {

    /**
     * Creates new form Interface_Par_Prox
     */
    private ArrayList<Ponto> points, closest;
    int state;

    public Interface_Par_Prox() {
        initComponents();
        points = new ArrayList<>();
        state = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Calcular = new javax.swing.JButton();
        Btn_limpar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel() {

            private static final long serialVersionUID = 1778590388624568285L;

            @Override
            public void paintComponent(Graphics g) {

                g.clearRect(0, 0, this.getWidth(), this.getHeight());
                g.setColor(Color.RED);

                for (Ponto p : points) {
                    g.fillOval((int) p.getX() - 3, (int) (getHeight() - p.getY() - 3), 5, 5);
                }

                if (state == 1) { // Desenhando o mais próximo
                    g.setColor(Color.BLACK);

                    for (Ponto p : closest) {
                        g.fillOval((int) p.getX() - 5, (int) (getHeight() - p.getY() - 4), 9, 9);
                    }
                }
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Geometria Computacional - Par mais próximo");

        Btn_Calcular.setText("Calcular");
        Btn_Calcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_CalcularMouseClicked(evt);
            }
        });

        Btn_limpar.setText("Limpar");
        Btn_limpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_limparMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 496, Short.MAX_VALUE)
                        .addComponent(Btn_limpar)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Calcular))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Calcular)
                    .addComponent(Btn_limpar))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_CalcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_CalcularMouseClicked
        // TODO add your handling code here:
        if (points.size() < 2) {
            return;
        }

        closest = ParMaisProximo.Fast(points);
        state = 1;

        jPanel1.repaint();
    }//GEN-LAST:event_Btn_CalcularMouseClicked

    private void Btn_limparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_limparMouseClicked
        // TODO add your handling code here:
        points = new ArrayList<>();
        state = 0;

        jPanel1.repaint();
    }//GEN-LAST:event_Btn_limparMouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        if (state == 0) {
            Ponto pi = new Ponto(evt.getX(), jPanel1.getHeight() - evt.getY());
            points.add(pi);
        }

        jPanel1.repaint();
    }//GEN-LAST:event_jPanel1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface_Par_Prox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface_Par_Prox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface_Par_Prox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface_Par_Prox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface_Par_Prox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Calcular;
    private javax.swing.JButton Btn_limpar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
