/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Modelo.Poligono;
import Modelo.Ponto;
import Modelo.Triangle;
import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Vector;

import Problemas.Algoritmo_Van_Gogh;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ângela
 */
public class Interface_Dobrar_Poligono extends javax.swing.JFrame {

    /**
     * Creates new form Interface_Dobrar_Poligono
     */
    private Poligono polygon; // para clacular triangulation
    private Poligono tempPolygon; // jogar na tela
    private ArrayList<Triangle> triangulation;
    int state;

    public Interface_Dobrar_Poligono() {
        initComponents();
        polygon = new Poligono();
        tempPolygon = new Poligono();
        state = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 =         jPanel1 = new javax.swing.JPanel() {
            @Override
            public void paintComponent(Graphics g) {

                g.clearRect(0, 0, this.getWidth(), this.getHeight());
                g.setColor(Color.GRAY);

                if (state == 1) {
                    for (Triangle t : triangulation) {
                        g.drawLine((int)t.getA().getX(), (int)(getHeight() - t.getA().getY()),
                            (int)t.getB().getX(), (int)(getHeight() - t.getB().getY()));
                        g.drawLine((int)t.getB().getX(), (int)(getHeight() - t.getB().getY()),
                            (int)t.getC().getX(), (int)(getHeight() - t.getC().getY()));
                        g.drawLine((int)t.getA().getX(), (int)(getHeight() - t.getA().getY()),
                            (int)t.getC().getX(), (int)(getHeight() - t.getC().getY()));
                    }
                }
                g.setColor(Color.BLACK);

                for (int i = 0; i < tempPolygon.tamanho(); i++) {
                    g.fillOval((int)tempPolygon.get(i).getX() - 3,
                        (int)(getHeight() - tempPolygon.get(i).getY() - 3), 5, 5);
                    g.drawLine((int)tempPolygon.get(i).getX(),
                        (int)(getHeight() - tempPolygon.get(i).getY()),
                        (int)tempPolygon.get((i+1) % tempPolygon.tamanho()).getX(),
                        (int)(getHeight() - tempPolygon.get((i+1) % tempPolygon.tamanho()).getY()));
                }
            }
        };
        ;
        Btn_Van_Gogh = new javax.swing.JButton();
        btn_Limpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Geometria Computacional - Dobrar Poligono");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        Btn_Van_Gogh.setText("Dobrar");
        Btn_Van_Gogh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Van_GoghMouseClicked(evt);
            }
        });

        btn_Limpar.setText("Limpar");
        btn_Limpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LimparMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 929, Short.MAX_VALUE)
                        .addComponent(btn_Limpar)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Van_Gogh)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Van_Gogh)
                    .addComponent(btn_Limpar))
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Van_GoghMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Van_GoghMouseClicked
        // TODO add your handling code here:
        if (polygon.tamanho() < 3) {
            return;
        }

        Poligono auxP = new Poligono();
        auxP.pontos = (Vector<Ponto>) polygon.getPontos().clone();

        triangulation = Algoritmo_Van_Gogh.slow(auxP);

        state = 1;

        jPanel1.repaint();
        
    }//GEN-LAST:event_Btn_Van_GoghMouseClicked

    private void btn_LimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LimparMouseClicked
        // TODO add your handling code here:
        polygon = new Poligono();
        tempPolygon = new Poligono();
        state = 0;

        jPanel1.repaint();
    }//GEN-LAST:event_btn_LimparMouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        if (state == 0) {
            Ponto pi = new Ponto(evt.getX(), jPanel1.getHeight() - evt.getY());
            polygon.insereVertice(pi);

            tempPolygon.removeVerticeDe(tempPolygon.tamanho() - 1);
            tempPolygon.insereVertice(pi);
            tempPolygon.insereVertice(pi);
        }

        jPanel1.repaint();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:
        if (state == 0) {
            Ponto pi = new Ponto(evt.getX(), jPanel1.getHeight() - evt.getY());
            tempPolygon.removeVerticeDe(tempPolygon.tamanho() - 1);
            tempPolygon.insereVertice(pi);
        }

        jPanel1.repaint();
    }//GEN-LAST:event_jPanel1MouseMoved

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:
        if (state == 0) {
            Ponto pi = new Ponto(evt.getX(), (jPanel1.getHeight() - evt.getY()));
            tempPolygon.insereVertice(pi);
        }

        jPanel1.repaint();
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        // TODO add your handling code here:
        if (state == 0) {
            tempPolygon.removeVerticeDe(tempPolygon.tamanho() - 1);
        }

        jPanel1.repaint();
    }//GEN-LAST:event_jPanel1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface_Dobrar_Poligono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface_Dobrar_Poligono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface_Dobrar_Poligono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface_Dobrar_Poligono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface_Dobrar_Poligono().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Van_Gogh;
    private javax.swing.JButton btn_Limpar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
