/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

/**
 *
 * @author Vitor
 */
import Modelo.Circulo;
import Modelo.Ponto;
import Problemas.Problemas_Classicos;
import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JOptionPane;

public class Interface_Area_Circulo extends javax.swing.JFrame {

    /**
     * Creates new form Interface_Area_Circulo
     */
    
    public Problemas_Classicos classicos;
    public Interface_Area_Circulo() {
        classicos = new Problemas_Classicos();
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Calcula_Area = new javax.swing.JButton();
        Btn_Calcula_Area.setEnabled(false);
        jLabel1 = new javax.swing.JLabel();
        Edt_text_raio = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel() {
            @Override
            public void paintComponent(Graphics g) {
                g.clearRect(0, 0, this.getWidth(), this.getHeight());
                g.setColor(Color.RED);

                if (circuloPronto) {
                    g.fillOval((int) aux.x, (int) aux.y, 7, 7);

                    g.drawOval((int) (aux.x - raio + 3), (int) (aux.y - raio + 3), (int) (raio * 2), (int) (raio * 2));

                }

            }
        };
        Btn_Limpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Geometria Computacional - Area Do Círculo");

        Btn_Calcula_Area.setText("Calcular Area");
        Btn_Calcula_Area.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Calcula_AreaMouseClicked(evt);
            }
        });

        jLabel1.setText("Digite o Raio:");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );

        Btn_Limpar.setText("Limpar");
        Btn_Limpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_LimparMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Edt_text_raio, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_Limpar)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Calcula_Area)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(23, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Calcula_Area)
                    .addComponent(Edt_text_raio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Limpar))
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Calcula_AreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Calcula_AreaMouseClicked
        // TODO add your handling code here:
        double resultado = classicos.areaCriculo(new Circulo(aux, raio));
        String texto = "Ponto: (" + aux.x + "," + aux.y + ")"
                + "\n\nArea do Circulo: " + resultado;
        JOptionPane.showMessageDialog(null, texto);
    }//GEN-LAST:event_Btn_Calcula_AreaMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        if (!circuloPronto) {

            if (Edt_text_raio.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Digite o Raio");
                return;
            }

            try {
                raio = Double.parseDouble(Edt_text_raio.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Formato Incorreto, Exemplo: 99.999");
                return;
            }

            aux = new Ponto(evt.getX(), evt.getY());

            Btn_Calcula_Area.setEnabled(true);
            circuloPronto = true;
            jPanel1.repaint();

        }
    }//GEN-LAST:event_jPanel1MouseClicked

    private void Btn_LimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_LimparMouseClicked
        // TODO add your handling code here:
        circuloPronto = false;
        Btn_Calcula_Area.setEnabled(false);
        Edt_text_raio.setText("");
        jPanel1.repaint();
    }//GEN-LAST:event_Btn_LimparMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface_Area_Circulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface_Area_Circulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface_Area_Circulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface_Area_Circulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface_Area_Circulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Calcula_Area;
    private javax.swing.JButton Btn_Limpar;
    private javax.swing.JTextField Edt_text_raio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    //=======================Minhas Váriáveis===================================
    public static double raio;
    public static int estado;
    private boolean circuloPronto = false;
    private boolean limpar = false;
    public static Ponto aux;
    //==========================================================================

}
